version: '3.6'

services:

  bot:
    build: .
    env_file: .env
    restart: on-failure
    logging:
      driver: journald

  server:
    build: .
    env_file: .env
    command: uvicorn server:app --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    restart: on-failure
    logging:
      driver: journald
